// <auto-generated />
namespace Jubilations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class remove_field_services : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_field_services));
        
        string IMigrationMetadata.Id
        {
            get { return "202303110702283_remove_field_services"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
